baseURL = "https://dexterduckworth.com"
theme = "LoveIt"
DefaultContentLanguage = "en"
enableRobotsTXT = true
publishDir = "docs"

[author]
name = "Dex Duckworth"
email = "dexter@dkwrth.com"

[params]

[params.home]
localTime = false
timeZone = "America/New_York"
timeFormat = "en-US"

[params.home.profile]
enable = true
avatarURL = "/images/profile.jpg"
title = "Dex Duckworth"
subtitle = "Machine Learning · Data Engineering  · Neurotechnology"
social = true
typeit = true

[params.header.title]
name = "Dex Duckworth"

[params.footer]
enable = true
hugo = true
copyright = true
author = true

[params.social]
GitHub = "dexterduck"
Twitter = "dexterduckworth"
Linkedin = "dexter-duckworth"
Email = "dexter@dkwrth.com"
RSS = true

[params.page.code]
copy = true
maxShownLines = 100

[params.page.share]
enable = true
Twitter = true
Linkedin = true
HackerNews = true
Reddit = true

[markup.highlight]
style = 'solarized-dark'
lineNos = true
noClasses = false

[languages]
[languages.en]
languageName = "English"
languageCode = "en-us"
weight = 1
title = "Dex Duckworth"

[[languages.en.menu.main]]
weight = 1
identifier = "about"
name = "About"
url = "/about/"

[[languages.en.menu.main]]
weight = 2
identifier = "posts"
name = "Posts"
url = "/posts/"

[[languages.en.menu.main]]
weight = 3
identifier = "tags"
name = "Tags"
url = "/tags/"
